### ISSUE TITLE
json cannot format

### ISSUE THREAD

**Issue by janreyho** [callumlocke/json-formatter#209] opened 2022-08-11 01:25 UTC
`{"errcode":0,"errmsg":"","result":{"total":1009,"page_nums":101,"list":[{"id":12125,"agent_id":1,"title":"朝阳无限芳菁苑8号楼1005室【二次拍卖】","region_1":20,"region_2":71,"area":14031,"trans_time":0,"market_price":"91400.0000","trans_price":"0.0000","begin_price":"64500.0000","begin_time":"2017-11-11 10:00:00","type_id":5,"limit_buy":1,"ctime":"2022-06-14 16:53:34","court_begin_time":0,"court_end_time":0,"trans_part_total":0,"area_type":1,"area_super":"140.31","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/not_prod\/dev\/pic\/20220616\/1655347754218041.png","url":"\/house\/12125","type_name":"住宅","agent_name":"消息一级-2","limit_buy_name":"限购","region_1_name":"朝阳","region_2_name":"甘露园","begin_price_wan":"645","market_price_wan":"914","trans_price_wan":"0"},{"id":9572,"agent_id":43,"title":"光大名筑9号楼4-0928室","region_1":20,"region_2":42,"area":13450,"trans_time":0,"market_price":"118000.0000","trans_price":"0.0000","begin_price":"77000.0000","begin_time":"2021-10-03 14:47:18","type_id":5,"limit_buy":1,"ctime":"2019-12-12 16:04:06","court_begin_time":0,"court_end_time":0,"trans_part_total":0,"area_type":1,"area_super":"134.50","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/pic\/20191213\/1576222325210241.jpeg","url":"\/house\/9572","type_name":"住宅","agent_name":"王禹翰","limit_buy_name":"限购","region_1_name":"朝阳","region_2_name":"亚运村小营","begin_price_wan":"770","market_price_wan":"1180","trans_price_wan":"0"},{"id":9492,"agent_id":23,"title":"金茂府东区2号楼1单元802室","region_1":20,"region_2":45,"area":20152,"trans_time":0,"market_price":"220000.0000","trans_price":"0.0000","begin_price":"183000.0000","begin_time":"2021-10-03 14:47:18","type_id":5,"limit_buy":2,"ctime":"2019-12-09 13:15:26","court_begin_time":0,"court_end_time":0,"trans_part_total":0,"area_type":1,"area_super":"201.52","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/pic\/20191210\/1575958062208923.jpeg","url":"\/house\/9492","type_name":"住宅","agent_name":"张洪斌","limit_buy_name":"不限购","region_1_name":"朝阳","region_2_name":"大望路","begin_price_wan":"1830","market_price_wan":"2200","trans_price_wan":"0"},{"id":9469,"agent_id":82,"title":"欧陆经典9号楼1201室","region_1":20,"region_2":42,"area":15327,"trans_time":0,"market_price":"105000.0000","trans_price":"0.0000","begin_price":"79000.0000","begin_time":"2021-10-03 14:47:18","type_id":5,"limit_buy":1,"ctime":"2019-12-06 13:29:11","court_begin_time":0,"court_end_time":0,"trans_part_total":0,"area_type":1,"area_super":"153.27","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/pic\/20191210\/1575941565208779.jpeg","url":"\/house\/9469","type_name":"住宅","agent_name":"侯达","limit_buy_name":"限购","region_1_name":"朝阳","region_2_name":"亚运村小营","begin_price_wan":"790","market_price_wan":"1050","trans_price_wan":"0"},{"id":9421,"agent_id":10,"title":"欧陆经典21号楼2305室","region_1":20,"region_2":42,"area":14302,"trans_time":0,"market_price":"92000.0000","trans_price":"0.0000","begin_price":"68500.0000","begin_time":"2021-10-03 14:47:18","type_id":5,"limit_buy":2,"ctime":"2019-12-04 16:19:40","court_begin_time":0,"court_end_time":0,"trans_part_total":0,"area_type":1,"area_super":"143.02","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/pic\/20191206\/1575626541208189.jpeg","url":"\/house\/9421","type_name":"住宅","agent_name":"田委","limit_buy_name":"不限购","region_1_name":"朝阳","region_2_name":"亚运村小营","begin_price_wan":"685","market_price_wan":"920","trans_price_wan":"0"},{"id":9223,"agent_id":11,"title":"珠江帝景B区201号楼2606室（复式）","region_1":20,"region_2":45,"area":27634,"trans_time":0,"market_price":"230000.0000","trans_price":"0.0000","begin_price":"143800.0000","begin_time":"2021-10-03 14:47:18","type_id":5,"limit_buy":1,"ctime":"2019-11-27 17:00:49","court_begin_time":1574233200,"court_end_time":1574236800,"trans_part_total":0,"area_type":1,"area_super":"276.34","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/pic\/20191023\/1571812816155060.jpeg","url":"\/house\/9223","type_name":"住宅","agent_name":"王嘉妮","limit_buy_name":"限购","region_1_name":"朝阳","region_2_name":"大望路","begin_price_wan":"1438","market_price_wan":"2300","trans_price_wan":"0"},{"id":9222,"agent_id":28,"title":"珠江帝景B区203号楼3单元2102室（复式）","region_1":20,"region_2":45,"area":26827,"trans_time":0,"market_price":"228000.0000","trans_price":"0.0000","begin_price":"140600.0000","begin_time":"2021-10-03 14:47:18","type_id":5,"limit_buy":1,"ctime":"2019-11-27 16:58:41","court_begin_time":1574233200,"court_end_time":1574233200,"trans_part_total":0,"area_type":1,"area_super":"268.27","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/pic\/20191023\/1571812490155055.jpeg","url":"\/house\/9222","type_name":"住宅","agent_name":"杨晓宇","limit_buy_name":"限购","region_1_name":"朝阳","region_2_name":"大望路","begin_price_wan":"1406","market_price_wan":"2280","trans_price_wan":"0"},{"id":9206,"agent_id":50,"title":"拂林园2号楼401室","region_1":20,"region_2":52,"area":17271,"trans_time":0,"market_price":"110000.0000","trans_price":"0.0000","begin_price":"100700.0000","begin_time":"2021-10-03 14:47:18","type_id":5,"limit_buy":1,"ctime":"2019-11-27 15:28:41","court_begin_time":0,"court_end_time":0,"trans_part_total":0,"area_type":1,"area_super":"172.71","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/pic\/20191127\/1574839741204539.jpeg","url":"\/house\/9206","type_name":"住宅","agent_name":"金娜","limit_buy_name":"限购","region_1_name":"朝阳","region_2_name":"北苑","begin_price_wan":"1007","market_price_wan":"1100","trans_price_wan":"0"},{"id":8945,"agent_id":36,"title":"团结湖中路北二条4号楼3单元303室","region_1":20,"region_2":96,"area":5680,"trans_time":0,"market_price":"46000.0000","trans_price":"0.0000","begin_price":"42000.0000","begin_time":"2019-12-20 10:00:00","type_id":5,"limit_buy":1,"ctime":"2019-11-19 09:51:31","court_begin_time":1575856800,"court_end_time":1575864000,"trans_part_total":0,"area_type":1,"area_super":"56.80","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/pic\/20191121\/1574307077163912.jpeg","url":"\/house\/8945","type_name":"住宅","agent_name":"张贺","limit_buy_name":"限购","region_1_name":"朝阳","region_2_name":"团结湖","begin_price_wan":"420","market_price_wan":"460","trans_price_wan":"0"},{"id":8906,"agent_id":27,"title":"大屯里小区106号楼703室","region_1":20,"region_2":36,"area":11023,"trans_time":0,"market_price":"73000.0000","trans_price":"0.0000","begin_price":"53400.0000","begin_time":"2021-10-03 14:47:18","type_id":5,"limit_buy":1,"ctime":"2019-11-15 16:51:12","court_begin_time":0,"court_end_time":0,"trans_part_total":0,"area_type":1,"area_super":"110.23","discount_rate":"0折","cover_url":"https:\/\/pic.fapai.cn\/pic\/20191118\/1574057803163077.jpeg","url":"\/house\/8906","type_name":"住宅","agent_name":"张为","limit_buy_name":"限购","region_1_name":"朝阳","region_2_name":"亚运村","begin_price_wan":"534","market_price_wan":"730","trans_price_wan":"0"}]},"is_inside_detail":0}`

the json cannot format，but https://www.json.cn/ can format。

**Comment by hirulez** [comment] 2022-08-11 09:24
same for me, it stopped working yesterday

**Comment by ErikMuir** [comment] 2022-08-11 14:06
> same for me, it stopped working yesterday

+1

**Comment by woolm110** [comment] 2022-08-11 16:14
> same for me, it stopped working yesterday

+1

**Comment by GoddessEyes** [comment] 2022-08-11 17:19
+ 1

**Comment by chabby-hao** [comment] 2022-08-12 01:55
+1

**Comment by miozus** [comment] 2022-08-12 05:16
+1  it works only once after downloaded.

**Comment by kitzberger** [comment] 2022-08-12 12:06
My workaround for now: duplicating the current tab.

**Comment by pinguluk** [comment] 2022-08-12 13:32
Working alternative https://chrome.google.com/webstore/detail/json-beautifier-editor/lpopeocbeepakdnipejhlpcmifheolpl/related?hl=en

**Comment by jeremytm** [comment] 2022-08-12 20:59
Finally made the switch to something else: https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh?hl=en 

Works great. The only thing I miss is being able to collapse all keys at a given level by holding a control key while clicking.

**Comment by bartkooijman** [comment] 2022-08-15 10:42
Chrome is reporting that there is an issue with the plugin calling navigator.platform in the content.js file. Maybe that is related to (if not the cause) of this issue:
![image](https://user-images.githubusercontent.com/13858027/184621234-3f39d42c-43d7-4af3-a907-49a88dab6fd9.png)

More info here: https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

**Comment by Aaron46** [comment] 2022-08-15 14:34
@bartkooijman like you said, it seems like the repo is using navigator.platform  
[ var mac = navigator.platform.indexOf('Mac') !== -1,](https://github.com/callumlocke/json-formatter/blob/d0abec784d330cdd7a7a92f19ea1f0578175fdef/extension/js/content.js#L329)

**Comment by woolm110** [comment] 2022-08-15 17:54
> Chrome is reporting that there is an issue with the plugin calling navigator.platform in the content.js file. Maybe that is related to (if not the cause) of this issue: ![image](https://user-images.githubusercontent.com/13858027/184621234-3f39d42c-43d7-4af3-a907-49a88dab6fd9.png)
> 
> More info here: https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html
> 
> PS: I am using Chrome 104 on Ubuntu

Updated to `navigator.userAgentData.platform.toLowerCase().indexOf('mac') !== -1` and it doesn't fix it. For now I've moved over to https://chrome.google.com/webstore/detail/json-viewer/gbmdgpbipfallnflgajpaliibnhdgobh and styled it to make it look like json-formatter

**Comment by xiaodongy** [comment] 2022-08-17 02:59
> same for me, it stopped working yesterday

+1

**Comment by callumlocke** [comment] 2022-08-22 15:57
Just getting to this.

The extension is still working for me on an up-to-date Chrome on macOS Monterey (104.0.5112.101 (Official Build) (arm64)).

Thanks @bartkooijman for the note about `navigator`.platform`, but it looks like that probably (?) isn't the cause of the issue here. Looks like that might become a problem in a future Chrome update though.

Can any of the "+1" folks see any error message in the console on JSON pages? If not, I'm wondering if this might actually be the same issue as #211. Is it possible you're all LastPass users by any chance? If so, then it should be fixed in the store soon, thanks to @bmamlin.

**Comment by Aaron46** [comment] 2022-08-22 16:36
@callumlocke I am using lastpass

**Comment by woolm110** [comment] 2022-08-22 16:41
I'm having the issue and using last pass, snap of my console errors, can't see anything that gives much info

<img width="737" alt="image" src="https://user-images.githubusercontent.com/3187079/185974129-5c3f0ffd-2e61-4f32-bb2e-014c6feb4cb9.png">

I tried the extension on Chrome without last pass and it works as expected

**Comment by ryan-th** [comment] 2022-08-22 16:45
@callumlocke - removing LastPass fixes this issue for me. I'll switch to watching #211. Thanks!

**Comment by jeremytm** [comment] 2022-08-22 21:17
Yep, I'm a lastpass user.

**Comment by callumlocke** [comment] 2022-08-23 06:37
OK thanks all, sounds like this is a dupe of #211. Which should now be fixed in v0.6.3 🤞

**Closed by callumlocke** 2022-08-23 06:37 UTC
